#server.servlet.context-path=/app
server:
  servlet:
    context-path: /app
  port : 10000
  
logging:
  level:
    '[com.sh.app]' : debug
    
# jsp를 view단으로 사용하는 경우
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring
    
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
  type-aliases-package: com.sh.app.menu
  mapper-locations:
  - classpath*:mapper/**/*-mapper.xml 
   
