server:
  servlet:
    context-path: 
  port : 10000
     

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@CRFJN9KBN0THKE3B_high?TNS_ADMIN=/Users/jaehoon/dev/Wallet_CRFJN9KBN0THKE3B
    username: admin
    password: Qazqaz7368!!
    
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
  type-aliases-package: com.sh.pinshot
  mapper-locations:
  - classpath*:mapper/**/*-mapper.xml 
   
